"""empty message

Revision ID: 313526b1ce21
Revises: 8399275cf955
Create Date: 2021-06-17 13:45:09.154429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313526b1ce21'
down_revision = '8399275cf955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apuestas', 'apuesta_a_equipo_A')
    op.drop_column('apuestas', 'apuesta_a_equipo_B')
    op.add_column('tarjeta_de_credito', sa.Column('ccv', sa.Integer(), nullable=False))
    op.add_column('tarjeta_de_credito', sa.Column('titular', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarjeta_de_credito', 'titular')
    op.drop_column('tarjeta_de_credito', 'ccv')
    op.add_column('apuestas', sa.Column('apuesta_a_equipo_B', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('apuestas', sa.Column('apuesta_a_equipo_A', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
