"""empty message

Revision ID: 8399275cf955
Revises: a06cbd52e9ea
Create Date: 2021-06-16 17:25:03.199895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8399275cf955'
down_revision = 'a06cbd52e9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidos', sa.Column('porcentaje_1', sa.Float(), nullable=False))
    op.add_column('partidos', sa.Column('porcentaje_2', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidos', 'porcentaje_2')
    op.drop_column('partidos', 'porcentaje_1')
    # ### end Alembic commands ###
