"""empty message

Revision ID: b7d67ea40948
Revises: 313526b1ce21
Create Date: 2021-06-17 15:24:19.456629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d67ea40948'
down_revision = '313526b1ce21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarjeta_de_credito', 'n_tarjeta')
    op.drop_column('tarjeta_de_credito', 'titular')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarjeta_de_credito', sa.Column('titular', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tarjeta_de_credito', sa.Column('n_tarjeta', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
