"""empty message

Revision ID: c5d358dad1d3
Revises: 
Create Date: 2021-06-13 11:32:29.277337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d358dad1d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('n_victorias', sa.Integer(), nullable=False),
    sa.Column('n_derrotas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_equipo')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('partidos',
    sa.Column('id_partido', sa.Integer(), nullable=False),
    sa.Column('equipo_a', sa.Integer(), nullable=False),
    sa.Column('equipo_b', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_a'], ['equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['equipo_b'], ['equipos.id_equipo'], ),
    sa.PrimaryKeyConstraint('id_partido')
    )
    op.create_table('usuario',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=60), nullable=False),
    sa.Column('usuario', sa.String(length=70), nullable=False),
    sa.Column('contrasenia', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('fecha_de_nacimiento', sa.Date(), nullable=False),
    sa.Column('ult_inicio_sesion', sa.DateTime(), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('apuestas',
    sa.Column('id_apuesta', sa.Integer(), nullable=False),
    sa.Column('id_partido', sa.Integer(), nullable=True),
    sa.Column('apuesta_a_equipo_A', sa.Boolean(), nullable=False),
    sa.Column('apuesta_a_equipo_B', sa.Boolean(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_partido'], ['partidos.id_partido'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_persona'], ),
    sa.PrimaryKeyConstraint('id_apuesta')
    )
    op.create_table('tarjeta',
    sa.Column('id_tarjeta', sa.Integer(), nullable=False),
    sa.Column('n_tarjeta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_persona'], ),
    sa.PrimaryKeyConstraint('id_tarjeta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarjeta')
    op.drop_table('apuestas')
    op.drop_table('usuario')
    op.drop_table('partidos')
    op.drop_table('rol')
    op.drop_table('equipos')
    # ### end Alembic commands ###
