"""empty message

Revision ID: f516bd3e635e
Revises: b7d67ea40948
Create Date: 2021-06-17 15:24:53.231554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f516bd3e635e'
down_revision = 'b7d67ea40948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarjeta_de_credito', sa.Column('n_tarjeta', sa.String(length=1000), nullable=False))
    op.add_column('tarjeta_de_credito', sa.Column('titular', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarjeta_de_credito', 'titular')
    op.drop_column('tarjeta_de_credito', 'n_tarjeta')
    # ### end Alembic commands ###
