"""empty message

Revision ID: fc1393e717d9
Revises: c5d358dad1d3
Create Date: 2021-06-13 11:48:00.099637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1393e717d9'
down_revision = 'c5d358dad1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apuestas', 'id_partido',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apuestas', 'id_partido',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
